server:
  host: user_service
  port: 8001

mongosh:
  host: mongodb
  port: 27017
  database: userDB
  collection: users
  # user: Bek10022006
  # password: Bek10022006

redis:
  host: redis
  port: 6379